version: '3.1'

services:
  db:
    image: postgres:14.7-alpine
    container_name: postgres
    hostname: db
    ulimits:
      nproc: 65535
    ports:
      - '5432:5432'
    networks:
      - bn
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U localhost']
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: '123456'

  flyway:
    image: flyway/flyway
    container_name: flyway
    networks:
      - bn
    command: -url=jdbc:postgresql://db:5432/postgres -user=localhost -password=123456 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      db:
        condition: service_healthy

  service:
    image: biolerplate
    container_name: service
    ports:
      - '5000:5000'
    env_file:
      - setup.env
    networks:
      - bn
    healthcheck:
      test:
        ['CMD', 'curl', '-f', 'http://localhost:5000/health']
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

networks:
  bn:
    name: biolerplate-network
